/**
 * GitHub Pages — Output Integration
 *
 * Writes plan data directly to a local clone of the portal repo, then
 * commits and pushes. GitHub Pages serves the result at a stable URL.
 *
 * Required config (workspace/state/secrets.yaml):
 *   github-pages:
 *     repoPath: "/absolute/path/to/walker-family-hub"
 *
 * Optional:
 *     autoPush: true   # set false to commit locally but not push (default: true)
 *
 * Run `npm run setup:portal` once to seed index.html and create the
 * required directory structure in the portal repo.
 *
 * Note: GitHub Pages on private repos requires GitHub Pro or higher.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";
import yaml from "js-yaml";
import { loadCalendarEvents } from "../../../scripts/calendar-utils.js";
import { BaseIntegration } from "../../_base/BaseIntegration.js";
import type { OutputIntegration, WeeklyPlan, ShoppingItem } from "../../_base/types.js";

interface GitHubPagesSecrets {
  repoPath: string;    // Absolute path to the local walker-family-hub repo
  autoPush?: boolean;  // Default: true
}

export default class GitHubPagesOutput extends BaseIntegration implements OutputIntegration {
  readonly id = "github-pages";
  readonly displayName = "GitHub Pages Portal";

  async healthCheck(): Promise<void> {
    const secrets = this.loadSecrets<GitHubPagesSecrets>();
    this.requireSecretKeys(secrets as unknown as Record<string, unknown>, ["repoPath"]);
    if (!existsSync(secrets.repoPath)) {
      throw new Error(
        `GitHub Pages repo not found at: ${secrets.repoPath}\n` +
          `Create the directory or update repoPath in workspace/state/secrets.yaml.`
      );
    }
    const gitDir = join(secrets.repoPath, ".git");
    if (!existsSync(gitDir)) {
      throw new Error(
        `${secrets.repoPath} is not a git repository.\n` +
          `Clone or init the portal repo first.`
      );
    }
  }

  async publishPlan(plan: WeeklyPlan): Promise<void> {
    const secrets = this.loadSecrets<GitHubPagesSecrets>();
    const dataDir = join(secrets.repoPath, "public", "data");
    mkdirSync(dataDir, { recursive: true });

    const js =
      `// Auto-generated by Family Hub planner — do not edit manually\n` +
      `window.PLAN_DATA = ${JSON.stringify(plan, null, 2)};\n`;

    writeFileSync(join(dataDir, "plan-data.js"), js, "utf8");
    this.writeFamilyData(secrets);
    this.commitAndPush(secrets, `chore: update plan data (${plan.weekStarting})`);
    console.log(`  GitHub Pages portal updated`);
  }

  async publishShoppingList(items: ShoppingItem[]): Promise<void> {
    const secrets = this.loadSecrets<GitHubPagesSecrets>();
    const dataDir = join(secrets.repoPath, "public", "data");
    mkdirSync(dataDir, { recursive: true });
    writeFileSync(join(dataDir, "shopping.json"), JSON.stringify(items, null, 2), "utf8");
    this.commitAndPush(secrets, "chore: update shopping list");
  }

  private writeFamilyData(secrets: GitHubPagesSecrets): void {
    const cwd = process.cwd();
    const readWsYaml = (rel: string): unknown[] => {
      const p = join(cwd, rel);
      if (!existsSync(p)) return [];
      const raw = yaml.load(readFileSync(p, "utf8"));
      return Array.isArray(raw) ? raw : [];
    };
    const data = {
      generatedAt: new Date().toISOString(),
      trips:       readWsYaml("workspace/trips.yaml"),
      escapeRooms: readWsYaml("workspace/escape-rooms.yaml"),
      movies:      readWsYaml("workspace/movies.yaml"),
    };
    const dataDir = join(secrets.repoPath, "public", "data");
    mkdirSync(dataDir, { recursive: true });
    const js =
      `// Auto-generated by Family Hub — do not edit manually\n` +
      `window.FAMILY_DATA = ${JSON.stringify(data, null, 2)};\n`;
    writeFileSync(join(dataDir, "family-data.js"), js, "utf8");

    // Calendar events: current week + next week for the week calendar view
    const calendarEvents = loadCalendarEvents(cwd);
    const calendarJs =
      `// Auto-generated by Family Hub — do not edit manually\n` +
      `window.CALENDAR_DATA = ${JSON.stringify({
        generatedAt: new Date().toISOString(),
        events: calendarEvents,
      }, null, 2)};\n`;
    writeFileSync(join(dataDir, "calendar-data.js"), calendarJs, "utf8");
  }

  private commitAndPush(secrets: GitHubPagesSecrets, message: string): void {
    const opts = { cwd: secrets.repoPath, stdio: "pipe" as const };
    try {
      execSync("git add -A", opts);
      // Check if there's anything to commit
      const status = execSync("git status --porcelain", opts).toString().trim();
      if (!status) return; // Nothing changed
      execSync(`git commit -m "${message}"`, opts);
      if (secrets.autoPush !== false) {
        execSync("git push", opts);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`Git operation failed in ${secrets.repoPath}: ${msg}`);
    }
  }
}
