/**
 * One-time setup for the GitHub Pages output integration.
 *
 * Run via:  npm run setup:portal
 *
 * What this does:
 *   1. Reads repoPath from workspace/state/secrets.yaml
 *   2. Copies index.html from outputs/web-portal/ into the portal repo
 *   3. Writes a placeholder plan-data.js so the portal loads without errors
 *   4. Commits and pushes the initial files
 *   5. Prints the expected GitHub Pages URL
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";
import yaml from "js-yaml";

const SECRETS_PATH = join(process.cwd(), "workspace", "state", "secrets.yaml");
const PORTAL_HTML_PATH = join(process.cwd(), "outputs", "web-portal", "index.html");

interface GitHubPagesSecrets {
  repoPath: string;
  autoPush?: boolean;
}

function loadSecrets(): GitHubPagesSecrets {
  if (!existsSync(SECRETS_PATH)) {
    console.error("✗ workspace/state/secrets.yaml not found.");
    process.exit(1);
  }
  const all = yaml.load(readFileSync(SECRETS_PATH, "utf8")) as Record<string, unknown>;
  const s = all["github-pages"] as GitHubPagesSecrets | undefined;
  if (!s?.repoPath) {
    console.error("✗ Missing github-pages.repoPath in workspace/state/secrets.yaml");
    console.error("  Add:");
    console.error("    github-pages:");
    console.error('      repoPath: "/absolute/path/to/walker-family-hub"');
    process.exit(1);
  }
  return s;
}

async function run() {
  console.log("\n🚀 GitHub Pages Portal Setup\n");

  const secrets = loadSecrets();
  const { repoPath } = secrets;

  // Validate the repo exists
  if (!existsSync(join(repoPath, ".git"))) {
    console.error(`✗ Not a git repo: ${repoPath}`);
    process.exit(1);
  }
  console.log(`  Portal repo: ${repoPath}`);

  // Create directory structure
  const dataDir = join(repoPath, "public", "data");
  mkdirSync(dataDir, { recursive: true });

  // Copy index.html
  if (!existsSync(PORTAL_HTML_PATH)) {
    console.error(`✗ Portal HTML not found at: ${PORTAL_HTML_PATH}`);
    process.exit(1);
  }
  const html = readFileSync(PORTAL_HTML_PATH, "utf8");
  writeFileSync(join(repoPath, "index.html"), html, "utf8");
  console.log("  ✓ index.html written");

  // Write placeholder plan-data.js
  const placeholder =
    `// Auto-generated by Family Hub planner — do not edit manually\n` +
    `window.PLAN_DATA = ${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        weekStarting: new Date().toISOString().slice(0, 10),
        summary: "Run the planner to generate your first weekly plan.",
        days: [],
        flags: [],
        actionItems: [],
        shoppingList: [],
      },
      null,
      2
    )};\n`;
  writeFileSync(join(dataDir, "plan-data.js"), placeholder, "utf8");
  console.log("  ✓ public/data/plan-data.js written");

  // Commit and push
  const opts = { cwd: repoPath, stdio: "pipe" as const };
  try {
    execSync("git add -A", opts);
    const status = execSync("git status --porcelain", opts).toString().trim();
    if (status) {
      execSync('git commit -m "chore: initialize Family Hub portal"', opts);
      console.log("  ✓ Committed");
      if (secrets.autoPush !== false) {
        execSync("git push", opts);
        console.log("  ✓ Pushed to GitHub");
      }
    } else {
      console.log("  ✓ No changes to commit (already up to date)");
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`  ✗ Git error: ${msg}`);
    process.exit(1);
  }

  // Derive the expected GitHub Pages URL from the remote
  let pagesUrl = "(check GitHub repo settings for your Pages URL)";
  try {
    const remote = execSync("git remote get-url origin", opts).toString().trim();
    // https://github.com/owner/repo.git  or  git@github.com:owner/repo.git
    const match = remote.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
    if (match) {
      const [, owner, repo] = match;
      pagesUrl = `https://${owner}.github.io/${repo}/`;
    }
  } catch {
    // Not critical
  }

  console.log("\n✅ Setup complete!\n");
  console.log(`   Portal URL (once Pages is enabled): ${pagesUrl}`);
  console.log(`\n   If you haven't enabled GitHub Pages yet:`);
  console.log(`   → GitHub repo → Settings → Pages → Source: Deploy from branch → main / (root)`);
  console.log(`   → Note: private repos require GitHub Pro`);
  console.log(`\n   Next: Run \`npm run plan\` to push your first weekly plan.\n`);
}

run().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
