#!/usr/bin/env tsx
/**
 * build-family-data.ts
 *
 * Reads workspace/trips.yaml, workspace/escape-rooms.yaml, and workspace/movies.yaml,
 * then writes public/data/family-data.js to the portal repo.
 *
 * Requires github-pages.repoPath to be set in workspace/state/secrets.yaml.
 *
 * Usage:
 *   npm run build:family-data
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import yaml from "js-yaml";
import { loadCalendarEvents } from "./calendar-utils.js";

const CWD = process.cwd();

function readWorkspaceYaml(rel: string): unknown[] {
  const p = join(CWD, rel);
  if (!existsSync(p)) {
    console.warn(`  ⚠  ${rel} not found — skipping`);
    return [];
  }
  const raw = yaml.load(readFileSync(p, "utf8"));
  return Array.isArray(raw) ? raw : [];
}

function loadRepoPath(): string {
  const secretsPath = join(CWD, "workspace", "state", "secrets.yaml");
  if (!existsSync(secretsPath)) {
    throw new Error("workspace/state/secrets.yaml not found");
  }
  const all = yaml.load(readFileSync(secretsPath, "utf8")) as Record<string, unknown>;
  const ghp = all["github-pages"] as { repoPath?: string } | undefined;
  if (!ghp?.repoPath) {
    throw new Error("github-pages.repoPath not set in workspace/state/secrets.yaml");
  }
  return ghp.repoPath;
}

const trips       = readWorkspaceYaml("workspace/trips.yaml");
const escapeRooms = readWorkspaceYaml("workspace/escape-rooms.yaml");
const movies      = readWorkspaceYaml("workspace/movies.yaml");

const data = {
  generatedAt: new Date().toISOString(),
  trips,
  escapeRooms,
  movies,
};

const repoPath = loadRepoPath();
const dataDir  = join(repoPath, "public", "data");
mkdirSync(dataDir, { recursive: true });

const js =
  `// Auto-generated by Family Hub — do not edit manually\n` +
  `window.FAMILY_DATA = ${JSON.stringify(data, null, 2)};\n`;

writeFileSync(join(dataDir, "family-data.js"), js, "utf8");
console.log(`✓ family-data.js written to ${repoPath}`);

// ── Calendar data (current week + next week for the week calendar view) ──
const calendarEvents = loadCalendarEvents(CWD);
const calendarJs =
  `// Auto-generated by Family Hub — do not edit manually\n` +
  `window.CALENDAR_DATA = ${JSON.stringify({
    generatedAt: new Date().toISOString(),
    events: calendarEvents,
  }, null, 2)};\n`;
writeFileSync(join(dataDir, "calendar-data.js"), calendarJs, "utf8");
console.log(`✓ calendar-data.js written (${calendarEvents.length} events)`);

// ── Strava activities ─────────────────────────────────────────────────────
const stravaStatePath = join(CWD, "workspace", "state", "strava-activities.yaml");
if (existsSync(stravaStatePath)) {
  const stravaRaw = yaml.load(readFileSync(stravaStatePath, "utf8")) as {
    generatedAt?: string;
    members?: Record<string, unknown[]>;
  } | null;
  const stravaJs =
    `// Auto-generated by Family Hub — do not edit manually\n` +
    `window.STRAVA_DATA = ${JSON.stringify(stravaRaw ?? { members: {} }, null, 2)};\n`;
  writeFileSync(join(dataDir, "strava-activities.js"), stravaJs, "utf8");
  const totalActivities = Object.values(stravaRaw?.members ?? {}).reduce((n, a) => n + a.length, 0);
  console.log(`✓ strava-activities.js written (${totalActivities} activities)`);
} else {
  console.log(`  strava-activities.yaml not found — skipping Strava data`);
}
